package com.sujula.model.auth;

import com.sujula.model.constant.SessionRevocationReason;
import com.sujula.model.user.User;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * One signed-in device, and the refresh token chain that keeps it signed in.
 *
 * <p>This is what makes {@code /me/sessions} and remote revocation possible: an
 * access token alone is a bearer credential nobody can withdraw before it
 * expires, so the thing that can actually be revoked has to be a row.
 *
 * <p><strong>The token itself is never stored.</strong> Only a SHA-256 hash of
 * it is, so a leaked database dump does not hand out live sessions — the same
 * reasoning that applies to passwords applies here, because a refresh token is a
 * password that happens to have been generated by us.
 *
 * <p>Rotation with replay detection is the security property worth understanding:
 * every refresh issues a new token and moves the old hash to
 * {@link #previousTokenHash}. Presenting the current token is normal. Presenting
 * the previous one means that token was captured and replayed — the legitimate
 * client has already moved on — so the whole session is revoked rather than
 * refreshed. Keeping exactly one generation of history is enough to catch that
 * without an unbounded audit chain.
 */
@Entity
@Table(name = "user_sessions",
       indexes = {
           @Index(name = "idx_session_user",     columnList = "user_id"),
           @Index(name = "idx_session_token",    columnList = "refresh_token_hash", unique = true),
           @Index(name = "idx_session_previous", columnList = "previous_token_hash"),
           @Index(name = "idx_session_expires",  columnList = "expires_at")
       })
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserSession {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Optimistic lock. Two tabs refreshing at the same moment would otherwise
     * both rotate the row and one would silently win, leaving the other client
     * holding a token the server has already forgotten.
     */
    @Version
    private Long version;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** SHA-256 of the live refresh token, hex encoded. Never the token. */
    @Column(name = "refresh_token_hash", nullable = false, unique = true, length = 64)
    private String refreshTokenHash;

    /** SHA-256 of the token this one replaced. Presenting it is a replay. */
    @Column(name = "previous_token_hash", length = 64)
    private String previousTokenHash;

    /** What the user recognises the device as, in the session list. */
    @Column(length = 120)
    private String deviceLabel;

    @Column(length = 400)
    private String userAgent;

    /** IPv6 needs 45 characters. */
    @Column(length = 45)
    private String ipAddress;

    @Column(length = 2)
    private String countryCode;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Moved forward on every refresh, so an idle device is visible as idle. */
    @Column(nullable = false)
    private LocalDateTime lastSeenAt;

    @Column(nullable = false)
    private LocalDateTime expiresAt;

    private LocalDateTime revokedAt;

    @Enumerated(EnumType.STRING)
    @Column(length = 30)
    private SessionRevocationReason revokedReason;

    /** Usable right now: not revoked, not past its expiry. */
    public boolean isActive() {
        return revokedAt == null && expiresAt != null && expiresAt.isAfter(LocalDateTime.now());
    }

    public void revoke(SessionRevocationReason reason) {
        if (revokedAt == null) {
            revokedAt = LocalDateTime.now();
            revokedReason = reason;
        }
    }
}
