package com.sujula.model.delivery;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.sujula.model.constant.DeliveryMode;
import com.sujula.model.constant.GeocodeConfidence;
import com.sujula.model.user.User;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Where a basket is going, resolved once and referred to afterwards.
 *
 * <p>Every price a shopper sees depends on the same three facts: where they are,
 * what currency they are shopping in, and how they intend to receive the goods.
 * Without somewhere to keep them, each of the cart, the quote, the serviceability
 * check and the checkout preview has to be handed the whole destination again —
 * and they drift, so the cart quotes one figure and checkout charges another. A
 * context is that answer, named once.
 *
 * <p><strong>It works for guests</strong>, which is most of the traffic on a
 * marketplace: someone browsing before they have an account still needs a
 * shipping estimate. So the row is not owned by a user in the usual sense.
 *
 * <p><strong>The id is the credential.</strong> There is no separate token
 * because a 256-bit unguessable id already is one — adding a second secret
 * alongside it would only create somewhere for the two to disagree. A guest
 * holds their context by possessing its id; that is why the id is random rather
 * than sequential, why it expires, and why it carries nothing that identifies a
 * person. When a signed-in user creates one, the row is additionally bound to
 * them and possession alone stops being enough.
 */
@Entity
@Table(name = "delivery_contexts",
       indexes = {
           @Index(name = "idx_delivery_context_user",    columnList = "user_id"),
           @Index(name = "idx_delivery_context_expires", columnList = "expiresAt")
       })
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DeliveryContext {

    /**
     * The opaque handle, and the whole of a guest's claim to this row.
     *
     * <p>Assigned rather than generated by the database: a sequential id would
     * let anyone read the next shopper's destination by adding one.
     */
    @Id
    @Column(length = 64, updatable = false)
    private String id;

    /**
     * The signed-in owner, when there is one.
     *
     * <p>Null for a guest, and that is not a gap — it is the difference between
     * "anyone holding the id" and "this person, holding the id". Both are
     * enforced on read.
     */
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    // ── Destination ──────────────────────────────────────────────────────────

    private Double latitude;
    private Double longitude;

    @Column(length = 255)
    private String addressLine;

    @Column(length = 120)
    private String city;

    @Column(length = 120)
    private String state;

    @Column(length = 20)
    private String postalCode;

    @Column(length = 2)
    private String countryCode;

    @Enumerated(EnumType.STRING)
    @Column(length = 20, nullable = false)
    @Builder.Default
    private GeocodeConfidence geocodeConfidence = GeocodeConfidence.NONE;

    // ── How the goods are received ───────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(length = 20, nullable = false)
    @Builder.Default
    private DeliveryMode mode = DeliveryMode.HOME_DELIVERY;

    /** The chosen hub, when the mode is collection. */
    private Long pickupPointId;

    /** The saved address this was built from, when it was built from one. */
    private Long addressId;

    // ── Resolved shopping context ────────────────────────────────────────────

    @Column(length = 3)
    private String currency;

    @Column(length = 10)
    private String language;

    @Column(length = 40)
    private String timezone;

    @Column(updatable = false)
    private LocalDateTime createdAt;

    /**
     * When this stops being usable.
     *
     * <p>Short-lived on purpose. The id is a bearer credential for a guest, and a
     * bearer credential that never expires is one that leaks into a browser
     * history, a shared link or an analytics log and stays useful. It also stops
     * a shopper being quoted against a destination they set last month.
     */
    @Column(nullable = false)
    private LocalDateTime expiresAt;

    public boolean isExpired() {
        return expiresAt == null || expiresAt.isBefore(LocalDateTime.now());
    }

    public boolean hasCoordinates() {
        return latitude != null && longitude != null;
    }

    /** Whether a signed-in caller is the one this belongs to. */
    public boolean belongsTo(Long userId) {
        return user != null && user.getId() != null && user.getId().equals(userId);
    }

    /**
     * Whether this row is anybody's in particular.
     *
     * <p>A guest context belongs to whoever holds the id; a user's belongs to
     * them alone.
     */
    public boolean isAnonymous() {
        return user == null;
    }
}
